### ISSUE TITLE
cw10

### ISSUE THREAD

**Issue by Luksquid** [LukasKalamarski/ps151192#10]
spr

**Comment by pjastr** [comment]
6.2.12 - kod nie spełnia zasad kompilacji

**Comment by pjastr** [comment]
6.2.16 - srednia powinna być przechowywania w typie `float` lub `double`

**Comment by pjastr** [comment]
6.2.2 - o coś innego tu chodzi, bylo na zajęciach

**Comment by pjastr** [comment]
6.2.6 - nie do końca o to chodzilo

**Comment by pjastr** [comment]
6.2.8 - argumenty funkcji w poleceniu byly inne

```c
void foo(int tab[][100],int n)
```

**Comment by pjastr** [comment]
proszę o ew poprawki do piątki 28.05 poza 6.2.6

**Comment by pjastr** [comment]
na razie brak poprawek, w przypadku dodania poproszę o ponowne otwarcie issue
